In [2]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import random
import pandas as pd
import io
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [3]:
ds = pd.read_csv('kag_risk_factors_cervical_cancer.csv')
ds

Age Number of sexual partners First sexual intercourse  \
0     18                       4.0                     15.0   
1     15                       1.0                     14.0   
2     34                       1.0                        ?   
3     52                       5.0                     16.0   
4     46                       3.0                     21.0   
..   ...                       ...                      ...   
853   34                       3.0                     18.0   
854   32                       2.0                     19.0   
855   25                       2.0                     17.0   
856   33                       2.0                     24.0   
857   29                       2.0                     20.0   

    Num of pregnancies Smokes Smokes (years) Smokes (packs/year)  \
0                  1.0    0.0            0.0                 0.0   
1                  1.0    0.0            0.0                 0.0   
2                  1.0    0.0            0.0                 0.0   
3                  4.0    1.0           37.0                37.0   
4                  4.0    0.0            0.0                 0.0   
..                 ...    ...            ...                 ...   
853                0.0    0.0            0.0                 0.0   
854                1.0    0.0            0.0                 0.0   
855                0.0    0.0            0.0                 0.0   
856                2.0    0.0            0.0                 0.0   
857                1.0    0.0            0.0                 0.0   

    Hormonal Contraceptives Hormonal Contraceptives (years)  IUD  ...  \
0                       0.0                             0.0  0.0  ...   
1                       0.0                             0.0  0.0  ...   
2                       0.0                             0.0  0.0  ...   
3                       1.0                             3.0  0.0  ...   
4                       1.0                            15.0  0.0  ...   
..                      ...                             ...  ...  ...   
853                     0.0                             0.0  0.0  ...   
854                     1.0                             8.0  0.0  ...   
855                     1.0                            0.08  0.0  ...   
856                     1.0                            0.08  0.0  ...   
857                     1.0                             0.5  0.0  ...   

    STDs: Time since first diagnosis STDs: Time since last diagnosis  \
0                                  ?                               ?   
1                                  ?                               ?   
2                                  ?                               ?   
3                                  ?                               ?   
4                                  ?                               ?   
..                               ...                             ...   
853                                ?                               ?   
854                                ?                               ?   
855                                ?                               ?   
856                                ?                               ?   
857                                ?                               ?   

    Dx:Cancer Dx:CIN Dx:HPV Dx Hinselmann Schiller Citology Biopsy  
0           0      0      0  0          0        0        0      0  
1           0      0      0  0          0        0        0      0  
2           0      0      0  0          0        0        0      0  
3           1      0      1  0          0        0        0      0  
4           0      0      0  0          0        0        0      0  
..        ...    ...    ... ..        ...      ...      ...    ...  
853         0      0      0  0          0        0        0      0  
854         0      0      0  0          0        0        0      0  
855         0      0      0  0          0        0        1      0  

In [4]:
Dn = 32

In [5]:
r = np.random.random((Dn,))
c = 0.00000000001

def f(x):
  
  print("------------------------------XXXXXXXXXXX---------------------------")
  print(x)
  print("------------------------------XXXXXXXXXXX---------------------------")
  
  s_i = 0

  for i in range(len(x[0])):
    if x[0][i]==1:
      s_i+=1
  if(s_i == 0):
    print("Error 0 features")
      
  # Defining X

  df = np.zeros((858,s_i))

  s_f = 0

  for i in range(len(x[0])):
    if x[0][i]==1:

      select_row = ds.iloc[:,i]
      select_arr = np.array(select_row)

      for ix in range(len(df)):

        if(select_row[ix]=='?'):
          df[ix][s_f] = -1
        else:
          df[ix][s_f] = select_arr[ix]
      s_f+=1
      
  #Defining y

  df_y = np.zeros((858,4))

  for i in range(4):
    select_row = ds.iloc[:,32+i]
    select_arr = np.array(select_row)

    for ix in range(len(df_y)):
      df_y[ix][i] = select_arr[ix]
      
  #Random Forest Prediction

  rf = RandomForestClassifier(n_estimators=1000, oob_score=True, random_state=123456)
  rf.fit(df, df_y)

  train_accuracy_rf = rf.score(df,df_y)

  return train_accuracy_rf

print(r)


[0.280274   0.06881898 0.85820962 0.58789581 0.43028526 0.94374023
 0.89452395 0.57824781 0.80591111 0.31091369 0.99737446 0.40286843
 0.24272417 0.1125532  0.9486187  0.65548863 0.3136695  0.85634027
 0.3012033  0.01267635 0.64299474 0.53557205 0.59605011 0.38231488
 0.12264714 0.26385981 0.57985973 0.81236809 0.54912901 0.72889331
 0.48616029 0.87386179]


In [6]:
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [7]:
class Chicken:

  def __init__(self):
    self.x_sample = np.random.randint(0,2,(1,Dn))
   
    while np.all(self.x_sample == 0):
      self.x_sample = np.random.randint(0,2,(1,Dn))
      
    self.x_real = self.x_sample
    self.next_position = np.random.random((Dn,))
    self.position = self.next_position
    self.fitness = -1
    self.group = -1
    self.hierarchy = "none"
  
  def evaluate(self):
    self.position = self.next_position
    self.x_real = self.x_sample
    self.fitness = f(self.x_real)
    
  
  def update_rooster(self,g,rooster):
    k = np.random.randint(0,g)
    
    while rooster[k].group == self.group:
      k = np.random.randint(0,g)
    
    #Calculating 'sigma_2'
    if rooster[k].group != self.group:
      if rooster[k].fitness >= self.fitness:
        sigma_2 = 1
        
      else:
        sigma_2 = np.exp((rooster[k].fitness - self.fitness) / (np.abs(self.fitness) + c))      # 'c' is the smallest constant to avoid dbz
        
    # Calculating 'next_position'
    Randn = np.random.normal(0,sigma_2)
    
    for ix in range(Dn):
      self.next_position[ix] = self.position[ix] * (1 + Randn)
    
    
    
  def update_hen(self,g,rooster):
    
    for ix in range(0,g):
      if rooster[ix].group == self.group:
        x_r1 = rooster[ix].position
        f_r1 = rooster[ix].fitness
        
    k = np.random.randint(0,g)
    
    while rooster[k].group == self.group:
      k = np.random.randint(0,g)
      
    if rooster[k].group != self.group:
      x_r2 = rooster[k].position
      f_r2 = rooster[k].fitness
      
    f_i = self.fitness
    x_i = self.position
      
    S1 = np.exp( (f_i-f_r1) / (np.abs(f_i) + c))      # 'c' is the smallest constant to avoid dbz
    S2 = np.exp((f_r2 - f_i))
    
    Rand = np.random.rand()
    
    for ix in range(Dn):
      self.next_position[ix] = (x_i[ix] + S1*Rand*(x_r1[ix] - x_i[ix]) + S2*Rand*(x_r2[ix] - x_i[ix]))
    
  def update_chik(self,FL,x_m):
    x_i = self.position
    
    for ix in range(Dn):
      self.next_position[ix] = (x_i[ix] + FL*(x_m[ix] - x_i[ix]))

In [11]:
y = []

class CSO:
  
  def __init__(self,N,Max_Gen,G,FL=0.5):
    
    #Number of Groups
    g = int(N/5)
    print("g = ",g)
    
    #Initialization of chicken population
    swarm = []
    
    for i in range(N):
      swarm.append(Chicken()) 
      swarm[i].evaluate()
      
    
    t=0
    
    while(t<Max_Gen):
      
      print("Inside While")
      
      if(t%G == 0):
        swarm.sort(key = lambda x:x.fitness , reverse = True)      # Sort swarm according to Fitness values of chickens
        
        print("Sorting Done")
        
        rooster = swarm[:g]
        chiks = swarm[-(2*g):]
        hens = swarm[-(N-g):-(2*g)]
        
        group = np.zeros((N,))       # Array for keeping track of groups to which chicken belong to
        
        # Hierarchy Setup
        for ix in range(g):
          swarm[ix].hierarchy = "rooster"
          swarm[-1-ix].hierarchy = "chik"
          swarm[-2-ix].hierarchy = "chik"
          
        for ix in range(g,(N-2*g)):
          swarm[ix].hierarchy = "hen"
          
        print("Hierarchy Set")  
        
        # Counter for number of chickens in each group  
        count_chiks = np.zeros((g,))
        count_roosters = np.zeros((g,))
        count_hens = np.zeros((g,))
          
        # Group assignment for Roosters
        for ix in range(g):
          r = np.random.randint(0,g)
          
          while count_roosters[r] >= 1:
            print("Inside While  ||  index: {0}  ||  r: {1}  ||  count_roosters[{2}]: {3}".format(ix,r,r,count_roosters[r]))
            r = np.random.randint(0,g)
          
          if count_roosters[r] < 1:
            swarm[ix].group = r+1
            count_roosters[r] = count_roosters[r] + 1
            group[ix] = r+1
        
        print("Group Assignment for Roosters done")
        
        # Group assignment for Hens and Chicks and Mother-Child Relationship
        
        mother_child_r = np.zeros((N,))
        for ix in range(g,(3*g)):
        
          r = np.random.randint(0,g)
          
          while count_hens[r] >= 2:
            r = np.random.randint(0,g)
            
          if count_hens[r] < 2:
            swarm[ix].group = r+1
            count_hens[r] = count_hens[r] + 1
            group[ix] = r+1
            
          r2 = np.random.randint(3*g,5*g)
          
          '''
          if ix+r2 >= N:
            while (ix+r2)>=N:
              print("ix: {0} || r2:{1} || ix+r2: {2} ".format(ix,r2,ix+r2))
              r2 = np.random.randint(2*g,4*g)
          '''
          
          while group[r2] !=0:
            r2 = np.random.randint(3*g,5*g)
            
          if group[r2] == -1:
            print("\n\n\n\ns See Me ... Do You Think I am Possible ?????")
            swarm[r2].group = r+1
            count_chiks[r] = count_chiks[r] + 1
            group[r2] = r+1
            
          mother_child_r[r2] = ix
          
        print("Group Assignment for Hens and Chicks done")
           
      for ix in range(N):
        print("\n\t For chicken number(ix): ",ix)
        
        if swarm[ix].hierarchy == "rooster":
          print("\t\tChicken is a Rooster")
          swarm[ix].update_rooster(g,rooster)
            
        elif swarm[ix].hierarchy == "hen":
          print("\t\tChicken is a Hen")
          swarm[ix].update_hen(g,rooster)
          
        elif swarm[ix].hierarchy == "chik":
          print("\t\tChicken is a Chick")
          m_ix = int(mother_child_r[ix])             # Index of it's mother
          x_m = swarm[m_ix].position                 # Position of it's mother
          
          swarm[ix].update_chik(FL,x_m)
          
        for jx in range(Dn):
          if sigmoid(swarm[ix].next_position[jx]) > np.random.random():
            swarm[ix].x_sample[0][jx] = 1
              
          else:
            swarm[ix].x_sample[0][jx] = 0 
          
        if f(swarm[ix].x_sample) > swarm[ix].fitness:
          swarm[ix].evaluate() 
                    

          
      y.append(swarm[0].fitness)
          
      print("Generation: {0} || Best Fitness: {1} || Best sample:{2} ".format(t,swarm[0].fitness,swarm[0].x_real))
          
      t = t+1

In [12]:
CSO(10,10,2,0.5)

g =  2
------------------------------XXXXXXXXXXX---------------------------
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[0 1 1 1 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0]]
------------------------------XX


	 For chicken number(ix):  7
		Chicken is a Chick
------------------------------XXXXXXXXXXX---------------------------
[[0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  8
		Chicken is a Chick
------------------------------XXXXXXXXXXX---------------------------
[[1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0]]
------------------------------XXXXXXXXXXX---------------------------
------------------------------XXXXXXXXXXX---------------------------
[[1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  9
		Chicken is a Chick
-----------------------


	 For chicken number(ix):  2
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  3
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  4
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  5
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0]]
------------------------------XXXXXXXXXXX--------


	 For chicken number(ix):  1
		Chicken is a Rooster
------------------------------XXXXXXXXXXX---------------------------
[[0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  2
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 1]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  3
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1]]
------------------------------XXXXXXXXXXX---------------------------

	 For chicken number(ix):  4
		Chicken is a Hen
------------------------------XXXXXXXXXXX---------------------------
[[1 0 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1]]
------------------------------XXXXXXXXXXX----